# example values
indexing-settings:
  sites:
    - url: https://playback.ru
      name: PlayBack.Ru
    - url: https://lenta.ru
      name: Лента.ру
    - url: https://skillbox.ru
      name: Skillbox

server:
  port: 8080

spring:
  datasource:
    username: root
    password: AllMightBoGdaN2003
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
